### ISSUE TITLE
est-il possible de rajouter une fonction permettant de répondre aux messages?

### ISSUE THREAD

**Issue by yapudjus** [romainflcht/igdm_terminal#5]
je ne suis pas en capacitée de le faire car je ne connais pas biens l'api, mais j'ai trouvé un projet en javascript permettant de répondre aux messages [ici](https://github.com/igdmapps/igdm), pas forcement besoins de le rajouter à l'interface, je me suis lancé pour écrire une interface avec le module `npyscreen`, en réutilisant une partie du code de ce repo, je publie mon avancement sur mon fork dans la branche `TUI-dev`

**Comment by romainflcht** [comment]
Après de nombreuses heures de recherche, de captures de paquets et de tests, j'ai enfin réussi à envoyer des messages à partir de mon interface. J'ai trouvé [ce repo](https://github.com/ohld/igbot) qui m'a beaucoup aidé, en plus de celui que vous m'avez donné. Pour l'instant, je n'ai pas encore intégré ce code correctement dans mon interface mais je le ferai cette semaine. J'espère que ce code vous sera utile 🙂

**Comment by yapudjus** [comment]
merci de tout le temps fourni, je me relance aussi sur linterface avec textual à partir de mercredi

**Comment by romainflcht** [comment]
C'est bon ! La fonction a été implémentée correctement. J'ai également apporté quelques modifications à votre code, notamment à la fonction 'delete_sessions', qui ne supprimait pas l'intégralité des fichiers. Je vous laisse y jeter un coup d'oeil !
