### ISSUE TITLE
après tentative d'envoi de message, mon token est invalidé

### ISSUE THREAD

**Issue by yapudjus** [romainflcht/igdm_terminal#6]
sur interface web
![image](https://github.com/romainflcht/igdm_terminal/assets/69390980/444b4d70-245e-43f4-ab61-b691a4738605)
sur interface tui
![image](https://github.com/romainflcht/igdm_terminal/assets/69390980/8a317b41-85f8-4aea-b090-6a664dd61117)

**Comment by romainflcht** [comment]
Le code indiqué (429) dit que le programme à fait trop de requêtes au serveur. En général, ce problème vient du fait qu'instagram bloque les requêtes lorsque le user-agent ne lui convient pas. Pour régler le problème : 

- Essayer de recréer une session avec un nouvel ID et un nouveau CSRF_Token
- Si cela ne marche pas il faut changer les User-Agents dans le fichier HEADERS.py. Vu ou l'erreur ce produit je pense qu'il s'agit d'un problème avec le MAIN_HEADERS, essayer de mettre le même user-agent que votre ordinateur voir si cela corrige le problème. 

Le message s'est t'il envoyé correctement ?

**Comment by yapudjus** [comment]
toujours un 429
![image](https://github.com/romainflcht/igdm_terminal/assets/69390980/55b78736-9d56-4904-bbfa-10677e72a979)
je me fais deco le client associé
le contenu de mon HEADERS.py
```───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: Documents/code/igdm_terminal/HEADERS.py
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # If you get any weird request error, try to modify the user agent of the main_header. 
   2   │ # If you can't send messages anymore, the BROADCAST_HEADER need to be modified with another device.
   3   │ 
   4   │ 
   5   │ # Header for every fetch requests such as fetch inbox data, thread content...
   6   │ MAIN_HEADERS = {
   7   │     'authority': 'www.instagram.com',
   8 ~ │     'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0', 
   9   │     'x-ig-app-id': '936619743392459',
  10   │ }
  11   │ 
  12   │ # Header used to send message, otherwise, we get a '403 Unauthorized' request status code. 
  13   │ BROADCAST_HEADERS = {
  14   │     'authority': 'www.instagram.com',
  15   │     'User-Agent': 'Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3;qcom; en_US; 180322800)',
  16   │     'x-ig-app-id': '936619743392459',
  17   │     'Accept-Encoding': 'gzip, deflate',
  18   │     'Accept': '*/*',
  19   │ }
  20   │ 
  21   │ if __name__ == '__main__': 
  22   │     print('This code is intended to be imported...')
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────```

**Comment by romainflcht** [comment]
J'ai modifié la gestion du header des requests en espérant que ça marche de vôtre coté. J'ai réussi a reproduire l'erreur que vous avez rencontré en changeant de compte Instagram et d'adresse IP, avec ce nouveau code je n'ai plus le problème... Avec ce nouveau header il est nécessaire de réimplémenter l'affichage des messages, je le ferai ultérieurement. Dites moi si ça marche de votre coté.

**Comment by romainflcht** [comment]
Bon, je viens de reéssayer le code, il y a de nouveaux problèmes je regarderai cela plus tard...

**Comment by romainflcht** [comment]
J'ai changé la gestion des headers. Pour le moment, le code marche à la deuxième authentification c'est à dire qu'il est nécéssaire de ce connecter une première fois, ce faire déconnecter, puis de ce reconnecter pour que toutes les fonctionnalités fonctionnent. Pour régler ce soucis, il faudrait reécrire la fonction de connexion pour passer par le mot de passe et récuperer tout les cookies qu'Instagram génère à la connexion. C'est à dire gérer la double authentification etc... Je me pencherai sur cette fonctionnalité quand j'aurai un peu plus de temps. Dites moi si le programme fonctionne chez vous.

**Comment by yapudjus** [comment]
après deconnection et reco:

``` -> (403) Error when fetching instagram server.
b'{"message":"login_required","error_title":"Vous avez \xc3\xa9t\xc3\xa9 d\xc3\xa9connect\xc3\xa9(e)","error_body":"Veuillez vous 
reconnecter.","logout_reason":8,"status":"fail"}'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Utiliser CTRL+C pour quitter le programme.
Pour un retour à la ligne, écrivez \n dans votre message.
ENTER pour envoyer, u pour mettre à jour les messages ou q pour quitter la conversation
Votre message :```

**Comment by romainflcht** [comment]
J'ai cette erreur uniquement lors de la première connexion... Je ne sais pas vraiment pourquoi Instagram déconnecte à ce moment, donc il est difficile de corriger le problème. Essayez d'insister un peu pour que Instagram comprenne qu'il s'agit de votre appareil. Peut-être que le fait de vous déconnecter de tous les appareils sauf de votre ordinateur pourrait aider. Je vais essayer de développer une meilleure fonctionnalité de connexion dès que possible...

**Comment by yapudjus** [comment]
serait-il possible d'importer les cookies d'une session déja existante?
![image](https://github.com/romainflcht/igdm_terminal/assets/69390980/c09d99a9-5ba1-4d5a-b3f7-bd6abfe2036c)

**Comment by romainflcht** [comment]
Vous pouvez importer vos cookies en rajoutant chaque champs dans le dictionnaire `cookies` dans le fichier `main.py` comme ceci : 

```python 

cookies = {
        'csrftoken': csrf_token,
        'sessionid': session_id,
        'rur': '',
        'shbid': '', 
        'shbts': '', 
        'ig_did': '', 
        'ds_user_id': '', 
        'oo': '', 
        'datr': '', 
        'mid': '',
    }
```

Je viens d'essayer mais étant donné que je n'ai pas le problème que vous avez, je ne sais pas si cela change quelque chose.

**Comment by yapudjus** [comment]
alors...
voiçi la liste des pb:
quand il sagit d'un raven_media:
pas de clé `item['raven_media']` donc j'ai remplacé temporairement la ligne `item_type = 'une ' + ('photo.' if item['raven_media'].get('media_type') else 'vidéo.')` dans format_data.py par `item_type = str(', '.join(item.keys()))`

après tentative d'envoi:
même pb
j'avais remplacé les cookies par
```cookies = {
        "mid":"ZH2FrEnzBDsE",
        "ig_did":"22B1EECB08",
        "datr":"vIV9ZiV",
        "shbid":"9922\05414663609759\0541727444767:01f756c3f8a6942d8127be7893851ddf6cdb4",
        "shbts":"1695908767\05414663609759\0541727444767:01f762111733feacb0",
        "sessionid":"14663dLoAdyehCzWMWEQ",
        "csrftoken":"fwZBJI9X3soECt",
        "rur":"ODN\054146636d571958340ad78302be17c5aba1a9e63a3714b845c5ae65bdc4",
        "ds_user_id":"14xxxxxx759"
    }
```
(cookies tronqué pour le post)
